<?php echo $this->view->getPartial('partials/top'); ?>

<div class="container-fluid">
    <div class="row" style="min-height: calc(100vh - 40px)">
        <?php echo $this->view->getPartial('partials/sidebar'); ?>

        <main class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4" role="main">
            <section class="widget">
                <div class="widget-body">
                    <div class="row">
                        <div class="col-3 admin-menu-container">

                            <ul id="admin_menu">

                                <?php if ($this->acl->userAllowed('admin', 'index')) { ?>
                                    <li class="nav flex-column <?php if ($this->dispatcher->getControllerName() === 'index') echo 'active'; ?>"
                                        aria-orientation="vertical">
                                        <a href="<?php echo $this->url->get('admin'); ?>">
                                            Tableau de bord
                                        </a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </div>

                        <div class="col-9">
                            <div id="admin_menu_content" class="tab-content container">
                                <?php echo $this->getContent(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    </div>
</div>


<style>
    .admin-menu-container {
        padding-right: 0;
        max-width: 350px;
    }
    #admin_menu {
        padding: .75rem .25rem;
    }
    #admin_menu > li {
        padding: .65rem 1rem;
        font-weight: 500;
    }
    #admin_menu > li a {
        text-decoration: none;
        color: #000;
    }
    #admin_menu > li a > .icon {
        width: 20%;
    }
    #admin_menu > li a > .row-title {
        width: 80%;
        padding-left: 15px;
    }
    #admin_menu > li.active {
        background-color: darkred;
        border-radius: 5px;
    }
    #admin_menu > li.active a {
        color: wheat;
        font-weight: bold;
    }
</style>