#!/usr/bin/env php
<?php

error_reporting(E_ALL);

define('BASE_PATH', __DIR__);

try {
    // Include composer's autoloader
    require_once BASE_PATH . '/vendor/autoload.php';

    // Handle console's application
    (new \Handler\ConsoleHandler())->handle();
}
catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    echo $e->getTraceAsString() . PHP_EOL;
    exit(255);
}
