#!/usr/bin/env php
<?php

error_reporting(E_ALL);

define('BASE_PATH', __DIR__);

try {
    // Include composer's autoloader
    require_once BASE_PATH . '/vendor/autoload.php';

    // Stream handle output
    ob_start();

    // Handle console's application
    (new \Handlers\ConsoleHandler($argv))->handle();

    // Output stream content and write it in log file
    $content = ob_get_clean();
    echo $content;
    file_put_contents('logs/'.time().'.log', $content);
}
catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    echo $e->getTraceAsString() . PHP_EOL;
    exit(255);
}
