version: '3.7'

services:
  app:
    build: .
    image: php-phalcon-7.4
    restart: always
    ports:
      - 8081:80
    networks:
      - overlay
    volumes:
      - ./:/app
      - ./resources/nginx.conf:/etc/nginx/sites-enabled/default:ro

  db:
    image: postgres
    restart: always
    networks:
      - overlay
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

networks:
  overlay: