<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <meta name="description" content="Phalcon Multisite">
        <meta name="keywords" content="phalcon multisite">
        <meta name="author" content="Lacji">
        
        <title>Phalcon Multisite</title>

        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('favicon.png')?>"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <?php $this->assets->outputCss('view_style'); ?>
    </head>

    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
    </body>
</html>
