<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="description" content="Phalcon Multisite">
        <meta name="keywords" content="phalcon multisite">
        <meta name="author" content="Lacji">

        <title>Application - Maintenance</title>

        <link rel="shortcut icon" href="<?php echo $this->url->get('favicon.ico')?>">

        <?php $this->assets->outputCss('main_style'); ?>
    </head>

    <body class="" style="text-align: center; margin-top: 10%">
        <img style="max-width: 150px;margin-bottom: 100px;" src="<?php echo $this->url->get('img/logo-large.png'); ?>" alt="">

        <h4>Votre application est actuellement en cours de maintenance...</h4>
        <h5>Veuillez nous excuser pour la gène occasionnée.</h5>
    </body>
</html>
