<?php if (!$this->view->hide_sidebar) { ?>
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="sidebar-sticky pt-3">
            <ul class="nav flex-column">

                <?php if ($this->acl->userAllowed('admin')) { ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->url->get('admin')?>">
                            <span data-feather="shopping-cart"></span>
                            Administration
                        </a>
                    </li>
                <?php } ?>

            </ul>
        </div>
    </nav>
<?php } ?>
