<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <?php if ($this->application->hasTenant()) { ?>
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3 text-center" href="<?php echo $this->url->get('') ?: ''; ?>">
            <?php echo $this->application->getTenant('name') ?: ''; ?>
        </a>
    <?php } else { ?>
        <div class="navbar-brand col-md-3 col-lg-2 mr-0 px-3 text-center"></div>
    <?php } ?>

    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="<?php echo $this->url->get('auth/logout')?>">Sign out</a>
        </li>
    </ul>
</nav>
