<section class="widget">
    <div class="row">
        <div class="col-12">
            <div class="widget-body">

                <div class="detail-block detail-block-success">
                    <div class="detail-block-text">Users</div>
                    <div class="detail-block-info"><?php echo $this->view->count_users ?></div>
                </div>

                <div class="detail-block detail-block-warning">
                    <div class="detail-block-text">Active Users</div>
                    <div class="detail-block-info"><?php echo $this->view->count_active_users ?></div>
                </div>

            </div>
        </div>
    </div>
</section>
