<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="Phalcon Multisite">
        <meta name="keywords" content="phalcon multisite">
        <meta name="author" content="Lacji">

        <title>Phalcon Multisite</title>

        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('public/img/favicon.png')?>"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>


        <script>
            window.onload = function () {
            var people = [{"name": "bob", "age": 32, "url": "https://example.com"}];

            var app = new Vue({
                delimiters: ['[[', ']]'],
                el: '#app',
                data: {
                    message: 'Hello Vue!',
                    people: people,
                },
                methods: {
                    greet: function(name) {
                        console.log('Hello from ' + name + '!')
                    }
                }
            })
            }
        </script>

        <?php $this->assets->outputCss('view_style'); ?>
    </head>

    <body>
        <div id="app">

            <li v-for="person in people">
                <a v-bind:href="person.url">[[ person.name ]]</a> <button v-on:click="greet(person.name)">hey</button>
            </li>


            <?php echo $this->getContent(); ?>
        </div>
    </body>
</html>
