<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Phalcon Multisite">
    <meta name="keywords" content="phalcon multisite">
    <meta name="author" content="jerome.auffret.ja@gmail.com">

    <title>Phalcon Multisite</title>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('public/img/favicon.ico')?>"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!--    <link href="--><?php //echo $this->url->get('api/assets/js/app.js') ?><!--" rel="preload" as="script">-->
<!--    <link href="--><?php //echo $this->url->get('api/assets/js/chunk-vendors.js') ?><!--" rel="preload" as="script">-->

    <?php $this->assets->outputCss('view_style'); ?>
</head>

<body>
    <div><?php echo $this->getContent(); ?><div>

    <div id="app"></div>
</body>

<?php //$this->assets->outputCss('view_script'); ?>

<!--<script src="--><?php //echo $this->url->get('api/assets/js/chunk-vendors.js') ?><!--"></script>-->
<!--<script src="--><?php //echo $this->url->get('api/assets/js/app.js') ?><!--"></script>-->

</html>
