<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Phalcon Multisite">
    <meta name="keywords" content="phalcon multisite">
    <meta name="author" content="jerome.auffret.ja@gmail.com">

    <title>Phalcon Multisite</title>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('public/img/favicon.ico')?>"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://unpkg.com/vue"></script>

    <link href="" rel="preload" as="script">
    <link href="<?php echo $this->url->get('assets/js/chunk-vendors.js') ?>" rel="preload" as="script">
    <link href="<?php echo $this->url->get('assets/js/auth.js') ?>" rel="preload" as="script">
    <link href="<?php echo $this->url->get('assets/js/hello-world.js/base') ?>" rel="preload" as="script">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get('assets/css/auth.css') ?>">

    <?php $this->assets->outputCss('view_style'); ?>
</head>

<body>
    <div><?php echo $this->getContent(); ?><div>
</body>

<?php //$this->assets->outputCss('view_script'); ?>

<script src="<?php echo $this->url->get('assets/js/chunk-vendors.js') ?>"></script>
<script src="<?php echo $this->url->get('assets/js/auth.js') ?>"></script>
<script src="<?php echo $this->url->get('assets/js/hello-world.js/base') ?>"></script>

</html>
