<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Phalcon Multisite">
    <meta name="keywords" content="phalcon multisite">
    <meta name="author" content="jerome.auffret.ja@gmail.com">

    <title>Phalcon Multisite</title>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('public/favicon.ico')?>"/>

    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css" />
    <link type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>

    <?php $this->assets->outputCss('view_style'); ?>
  </head>

  <body>
    <div class="wrapper">
      <div id="<?php echo $this->view->page_slug ?>">
        <?php echo $this->getContent(); ?>
      </div>
    <div>
  </body>

  <script src="//unpkg.com/jquery@3.3.1/dist/jquery.min.js"></script>
  <script src="//unpkg.com/vue@latest/dist/vue.min.js"></script>
  <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

  <?php echo $this->assets->outputJs('view_script'); ?>
</html>
