<div class="container">
    <div class="col-lg-6 col-md-8 col-sm-12 mx-auto">

        <div class="header">
            <div class="media">
                <img src="<?php echo $this->url->get('logo-large.png'); ?>" alt="Login Logo" class="mx-auto" style="max-width: 150px;">
            </div>
        </div>

        <hello-world msg="Welcome !"></hello-world>

        <login-form></login-form>

    </div>
</div>