<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>500</title>
</head>

<body>

<div id="internal-error">
    <div class="internal-error">
        <div class="internal-error-500">
            <h1>500</h1>
        </div>
        <h2>Oops! Quelques chose s'est mal passé !</h2>
        <p><a href="<?php echo $this->url->get('') ?>">Return to homepage</a></p>
    </div>
</div>

</html>


<style>
    * {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    body {
        padding: 0;
        margin: 0;
    }
    #internal-error {
        position: relative;
        height: 100vh;
    }
    #internal-error .internal-error {
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }
    .internal-error {
        max-width: 767px;
        width: 100%;
        line-height: 1.4;
        text-align: center;
        padding: 15px;
    }
    .internal-error .internal-error-500 {
        position: relative;
        height: 220px;
    }
    .internal-error .internal-error-500 h1 {
        font-family: 'Kanit', sans-serif;
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        font-size: 186px;
        font-weight: 200;
        margin: 0px;
        background: linear-gradient(130deg, #ffa34f, #be0f26);
        color:transparent;
        -webkit-background-clip: text;
        background-clip: text;
        text-transform: uppercase;
    }
    .internal-error h2 {
        font-family: 'Kanit', sans-serif;
        font-size: 33px;
        font-weight: 200;
        text-transform: uppercase;
        margin-top: 0px;
        margin-bottom: 25px;
        letter-spacing: 3px;
    }
    .internal-error p {
        font-family: 'Kanit', sans-serif;
        font-size: 16px;
        font-weight: 200;
        margin-top: 0px;
        margin-bottom: 25px;
    }
    .internal-error a {
        font-family: 'Kanit', sans-serif;
        color: #ff6f68;
        font-weight: 200;
        text-decoration: none;
        border-bottom: 1px dashed #ff6f68;
        border-radius: 2px;
    }
    .internal-error-social>a {
        display: inline-block;
        height: 40px;
        line-height: 40px;
        width: 40px;
        font-size: 14px;
        color: #ff6f68;
        border: 1px solid #efefef;
        border-radius: 50%;
        margin: 3px;
        -webkit-transition: 0.2s all;
        transition: 0.2s all;
    }
    .internal-error-social>a:hover {
        color: #fff;
        background-color: #ff6f68;
        border-color: #ff6f68;
    }
    @media only screen and (max-width: 480px) {
        .internal-error .internal-error-500 {
            position: relative;
            height: 168px;
        }

        .internal-error .internal-error-500 h1 {
            font-size: 142px;
        }

        .internal-error h2 {
            font-size: 22px;
        }
    }
</style>
