<div class="row">
    <?php if($this->view->application_list->count()) { ?>
        <?php foreach ($this->view->application_list as $application) { ?>
            <div class="application-item col-3">
                <a href="<?php echo $this->url->get('auth/application/switchApplication/'.$application->getId()) ?>">
                    <?php echo $application->getName(); ?>
                </a>
                <p><?php echo $application->getDescription(); ?></p>
            </div>
        <?php } ?>
    <?php } else { ?>
        <h3>Applications not found</h3>
    <?php } ?>
</div>